# This is a basic workflow to help you get started with Actions

name: BlazorDemo

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # build blazor app
    - name: Build blazor app
      run: dotnet build --configuration Release

    # publish blazor app to "staging" directory
    - name: Publish app
      run: dotnet publish --configuration Release --output staging
    
    # publish "staging" directory as build artifact
    - name: Publish build artifacts for deployment
      uses: actions/upload-artifact@master
      with:
        name: webapp
        path: staging

  deployToStaging:
    # This job depends on build job
    needs: [build]

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # download build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@master
        with:
          name: webapp

      - name: Debug
        run: |
          echo 'ls'
          ls
          echo 'cd wwwroot'
          cd wwwroot
          echo 'ls'
          ls
